####################################################################################################
# Simulation
equations = "euler"
# equations = "linearscalaradvection"
# advectionvelocity = [1.0, 1.0] # Need only for linarscalaradvection

initial_conditions = "isentropic_vortex"
amr_indicator = "isentropic_vortex"
# initial_conditions = "constant"
surface_flux_type = "laxfriedrichs"
# sources = 
t_start = 0.0
t_end   = 120.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3

################################################################################
# Carpenter
# cfl = 0.7#0.6
################################################################################
# Paired RK/multi
cfl = 1.9
time_integration_scheme = "paired_rk_2_multi"
# alive_interval = 1
# optimized_paired_rk = false
################################################################################
# Paired RK/single
# time_integration_scheme = "paired_rk_2_s"

# cfl = 3.1
# n_stages = 16
# derivative_evaluations = 16

# cfl = 1.5
# n_stages = 16
# derivative_evaluations = 8

# cfl = 0.75
# n_stages = 16
# derivative_evaluations = 4

# cfl = 0.35
# n_stages = 16
# derivative_evaluations = 2
################################################################################

n_steps_max = 10000
analysis_interval = 200


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [-10, -10]
coordinates_max =  [10, 10]
initial_refinement_level = 3
amr_interval = 5
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 50
solution_variables = "primitive"
restart_interval = 0
